<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [5]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [18]:
%%sql

SELECT * FROM customer LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14
5,185,2,1990-08-01,2029-05-28,Australia,female,Mrs.,Gabrielle,B,Castella,...,2469,AU,Australia,1980-02-23,40,Management dietitian,d.e.m.o.,1997 Alpina B6,-29.01,152.84
6,189,7,2008-07-05,2017-11-01,Australia,female,Ms.,Hayley,C,Jull,...,3377,AU,Australia,1960-04-18,60,Sculptor,Asian Plan,2006 Alpina B5,-37.34,142.91
7,210,2,1980-09-28,2030-05-08,Australia,female,Mrs.,Natalie,L,Hilder,...,2632,AU,Australia,1950-11-23,70,Motel desk clerk,Enrich Garden Services,1995 Ford Fairlane,-36.84,149.05
8,225,7,1985-06-25,2017-09-25,Australia,male,Mr.,Hunter,J,Hutchins,...,3763,AU,Australia,1978-07-20,42,Teletype operator,Mr. Good Buys,2012 Lexus GX,-37.51,145.44
9,243,2,1982-02-07,2027-02-09,Australia,female,Ms.,Maya,J,Atherton,...,2446,AU,Australia,1954-05-15,66,Pilates instructor,Franklin Music,1995 Chevrolet Caprice,-31.36,152.39

In [21]:
%%sql

SELECT orderdate,
  quantity * unitprice AS total_price,
  c.customerkey,
  c.gender,
  c.latitude,
  c.longitude
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE orderdate::date BETWEEN '2024-01-01' AND '2024-04-30'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10131 rows affected.

        orderdate  total_price  customerkey  gender  latitude  longitude
0      2024-01-01       115.00       831848  female     51.87       5.77
1      2024-01-01         4.74       340766    male     43.65     -79.48
2      2024-01-01        86.00      1831519  female     39.26     -76.74
3      2024-01-01       341.40      1739511    male     37.25    -121.91
4      2024-01-01       777.00      1739511    male     37.25    -121.91
...           ...          ...          ...     ...       ...        ...
10126  2024-04-16        14.97      1033983    male     57.99      -3.91
10127  2024-04-16       539.97      1033983    male     57.99      -3.91
10128  2024-04-16         4.74      1223228    male     42.36    -123.00
10129  2024-04-16        86.28      1258864    male     32.87    -117.18
10130  2024-04-16        13.98      1258864    male     32.87    -117.18

[10131 rows x 6 columns]

In [31]:
%%sql

SELECT
  SUM(quantity * unitprice)AS total_price,
  c.gender
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE orderdate::date BETWEEN '2024-01-01' AND '2024-04-30'
GROUP BY gender

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

   total_price  gender
0   4106730.59  female
1   4497373.57    male

In [33]:
%%sql

SELECT gender,
  COUNT(gender) AS gender_count
FROM customer
GROUP BY gender

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

   gender  gender_count
0  female         51927
1    male         53063